[build]
  command = "pip install -r requirements.txt && python -c \"from app import app, db; db.create_all()\""
  publish = "static"
  functions = "api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["flask"]

[build.environment]
  PYTHON_VERSION = "3.11"
  FLASK_APP = "app.py"
  FLASK_ENV = "production"
  PYTHONUNBUFFERED = "true"

[dev]
  command = "python app.py"
  port = 5000
  publish = "static"
  targetPort = 5000

[dev.environment]
  FLASK_APP = "app.py"
  FLASK_ENV = "development"
  FLASK_DEBUG = "1"
